# Generated by Django 4.1.6 on 2023-02-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
