# Generated by Django 4.1.6 on 2023-02-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
