# Generated by Django 4.1.6 on 2023-02-10 14:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_delete_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='name',
            new_name='game_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='name',
        ),
        migrations.AddField(
            model_name='tournament',
            name='admin',
            field=models.CharField(default='Test', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 14, 22, 57, 60728, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='tournament',
            name='game',
            field=models.CharField(blank=True, choices=[('FIFA', 'Fifa'), ('Super Smash Bros Ultimate', 'Ssbu'), ('Dragon Ball FighterZ', 'Dbfz')], max_length=50, null=True, verbose_name='Jeu'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='nb_players',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(8, 'Le nombre de participants est imposé à 8 pour le moment'), django.core.validators.MaxValueValidator(8, 'Le nombre de participants est imposé à 8 pour le moment')], verbose_name='Nombre de participants'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Joueur 1'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player2',
            field=models.CharField(default='Bot', max_length=20, verbose_name='Joueur 2'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Joueur 3'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Joueur 4'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Joueur 5'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player6',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Joueur 6'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player7',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Joueur 7'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player8',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Joueur 8'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_infos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du tournoi'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 14, 22, 57, 61145, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Saisissez une adresse courriel valide'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tournament_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
