# Generated by Django 4.1.6 on 2023-02-12 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_rename_name_games_game_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 15, 13, 16, 834147, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Joueur 2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 15, 13, 16, 834480, tzinfo=datetime.timezone.utc)),
        ),
    ]
