# Generated by Django 4.1.6 on 2023-02-13 11:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0021_alter_games_created_at_alter_tournament_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='player9',
        ),
        migrations.AlterField(
            model_name='games',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 11, 10, 54, 316993, tzinfo=datetime.timezone.utc), verbose_name='Ajouté le'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 11, 10, 54, 317302, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.games', verbose_name='Jeu'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.user', verbose_name='Joueur 1'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.user', verbose_name='Joueur 2'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.user', verbose_name='Joueur 3'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.user', verbose_name='Joueur 4'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.user', verbose_name='Joueur 5'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.user', verbose_name='Joueur 6'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.user', verbose_name='Joueur 7'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tournaments.user', verbose_name='Joueur 8'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 11, 10, 54, 316719, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
    ]
