# Generated by Django 4.1.7 on 2023-02-15 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0022_remove_tournament_player9_alter_games_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='game_description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='games',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 15, 28, 8, 310614, tzinfo=datetime.timezone.utc), verbose_name='Ajouté le'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='admin',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 15, 28, 8, 310871, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 15, 28, 8, 310375, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
    ]
