# Generated by Django 4.1.6 on 2023-02-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0023_games_game_description_alter_games_created_at_and_more'),
        ('tournaments', '0026_alter_games_created_at_alter_tournament_created_at_and_more'),
    ]

    operations = [
    ]
