# Generated by Django 4.1.6 on 2023-02-23 11:07

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0029_alter_games_created_at_alter_tournament_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 11, 7, 39, 387793, tzinfo=datetime.timezone.utc), verbose_name='Ajouté le'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 11, 7, 39, 388216, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.games', verbose_name='Jeu'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='nb_players',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(8, 'Le nombre de participants est imposé à 8 pour le moment'), django.core.validators.MaxValueValidator(8, 'Le nombre de participants est imposé à 8 pour le moment')], verbose_name='Nombre de participants'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player1',
            field=models.CharField(max_length=20, null=True, verbose_name='Joueur 1'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player2',
            field=models.CharField(max_length=20, null=True, verbose_name='Joueur 2'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player3',
            field=models.CharField(max_length=20, null=True, verbose_name='Joueur 3'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player4',
            field=models.CharField(max_length=20, null=True, verbose_name='Joueur 4'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player5',
            field=models.CharField(max_length=20, null=True, verbose_name='Joueur 5'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player6',
            field=models.CharField(max_length=20, null=True, verbose_name='Joueur 6'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player7',
            field=models.CharField(max_length=20, null=True, verbose_name='Joueur 7'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='player8',
            field=models.CharField(max_length=20, null=True, verbose_name='Joueur 8'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Heure de début'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom du tournoi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 11, 7, 39, 387466, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
