# Generated by Django 4.1.7 on 2023-02-24 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0033_tournament_game_image_path_alter_games_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='game_image_path',
        ),
        migrations.AddField(
            model_name='games',
            name='game_image_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 10, 2, 19, 752938, tzinfo=datetime.timezone.utc), verbose_name='Ajouté le'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 10, 2, 19, 753119, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 10, 2, 19, 752717, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
    ]
