# Generated by Django 4.1.7 on 2023-02-24 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0034_remove_tournament_game_image_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='game_image',
            field=models.ImageField(blank=True, null=True, upload_to='games/'),
        ),
        migrations.AlterField(
            model_name='games',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 10, 36, 53, 22294, tzinfo=datetime.timezone.utc), verbose_name='Ajouté le'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 10, 36, 53, 22550, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 10, 36, 53, 22078, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
    ]
