# Generated by Django 4.1.7 on 2023-02-24 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0035_games_game_image_alter_games_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='game_image_path',
        ),
        migrations.AlterField(
            model_name='games',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 10, 39, 27, 284882, tzinfo=datetime.timezone.utc), verbose_name='Ajouté le'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 10, 39, 27, 285134, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 10, 39, 27, 284661, tzinfo=datetime.timezone.utc), verbose_name='Créé le'),
        ),
    ]
