# Generated by Django 4.1.6 on 2023-02-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0034_alter_games_created_at_alter_tournament_created_at_and_more'),
        ('tournaments', '0036_remove_games_game_image_path_alter_games_created_at_and_more'),
    ]

    operations = [
    ]
